### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by fknfilewalker** [Mira-13/figure-gen#4]
Is it possible to draw an image above another image and is it possible to have plots with a legend?

**Comment by pgrit** [comment]
The two plotting modules have some very basic legend support:
https://github.com/Mira-13/figure-gen/blob/e4cb1d9ea1841980b4dc90953325e1a8c6dfb510/figuregen/matplot_lineplot.py#L295
https://github.com/Mira-13/figure-gen/blob/e4cb1d9ea1841980b4dc90953325e1a8c6dfb510/figuregen/pgf_lineplot.py#L54

Images above other images are not directly supported. Depending on the use-case, what I'd do there is either:
1. "Bake" the two images into one (if the top image does not extend outside the bounds of the bottom one)
2. Add the top image in a post-process. E.g., by using the .tikz backend. The generated tikz and html codes assign unique IDs to all elements, so you should be able to easily anchor a new node to an existing image based on its index in a grid.

**Comment by pgrit** [comment]
Example:
```python
plot = fig.PgfLinePlot(0.6, [(x, time), (x, heuristic), (x, ratio)])
if i == 1:
    plot.set_legend(["Time", "Heuristic", "Ratio"], fontsize_pt=7, pos=(0.02, 1), anchor="north west")
```

generates:
![image](https://user-images.githubusercontent.com/12607894/168990627-4e93889b-b11d-436a-a5f4-64cab9f2c155.png)

**Comment by fknfilewalker** [comment]
I see, thanks :)
